### ISSUE TITLE
tutorial 3- R and Python

### ISSUE THREAD

**Issue by shospital** [nmfs-opensci/EDMW-EarthData-Workshop-2024#6]
- [x] modify R
- [x] modify Python
- [x] test on dhub
- [x] write notes for users

**Comment by shospital** [comment]
@MattGrossi-NOAA @EmilyMarkowitz-NOAA Could you test the tutorial 3 R and Python on dhub?
It works for me on my dhub but would like to make sure it works for other users as well.
mahalo!

**Comment by MattGrossi-NOAA** [comment]
Python tutorial: I had to manually install regionmask with pip the first time. Then the import cell returned "ERROR 1: PROJ: proj_create_from_database: Open of /srv/conda/envs/notebook/share/proj failed" -- but everything thereafter ran without any discernable problems.

R: Everything worked fine.

Will inspect the content more carefully next week.

**Comment by shospital** [comment]
@MattGrossi-NOAA thank you Matt!
Yes the regionmask didn't seem to be installed yet. I had created an issue for Eli to add it to the packages. 

Re: proj warning, we have had that issue. When you run it again, the error disappears.  Will take a look at it.
Thank you!
